# Generated by Django 5.2.8 on 2025-12-08 21:10

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('article', models.TextField()),
                ('chunk', pgvector.django.vector.VectorField(dimensions=3000)),
                ('last_change', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Law',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('publish_date', models.DateField()),
                ('name', models.CharField(max_length=256)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('article', models.TextField()),
                ('chunk', pgvector.django.vector.VectorField(dimensions=3000)),
                ('paragraph_number', models.IntegerField()),
                (
                    'id_article',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name='paragraph',
                        serialize=False,
                        to='api.article',
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='id_law',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='article', to='api.law'
            ),
        ),
        migrations.AddField(
            model_name='law',
            name='id_status',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='law', to='api.status'
            ),
        ),
        migrations.AddField(
            model_name='article',
            name='id_status',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='article', to='api.status'
            ),
        ),
        migrations.AddField(
            model_name='article',
            name='id_theme',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='article', to='api.theme'
            ),
        ),
    ]
